services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: asl1_db
    ports:
      - "5432:5432"

  backend:
    build: .
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: 123456
      PGDATABASE: asl1_db
      PGPORT: 5432
    depends_on:
      - db
